spring.application.name=escape-room-clara-backend

# Core
spring.profiles.active=postgres

# API endpoints
api-endpoint=api/v1

# Docker
spring.docker.compose.enabled=true

# JWT signing key
jwt.key=${JWT_SECRET_KEY}


# reCAPTCHA secret key
recaptcha.secret-key=${RECAPTCHA_SECRET_KEY}
